package com.lz.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lz.bean.InvestTable;
import com.lz.bean.MemberInfo;
import com.lz.bean.Order;
import com.lz.bean.OrderByProduct;
import com.lz.bean.ProductTable;
import com.lz.bean.User;
import com.lz.bean.FileInfo;

import com.lz.dao.InvestTableDao;
import com.lz.dao.MemberInfoDao;
import com.lz.dao.OrderDao;
import com.lz.dao.OrderByProductDao;
import com.lz.dao.ProductTableDao;
import com.lz.dao.UserDao;
import com.lz.dao.FileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig investTableDaoConfig;
    private final DaoConfig memberInfoDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig orderByProductDaoConfig;
    private final DaoConfig productTableDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig fileInfoDaoConfig;

    private final InvestTableDao investTableDao;
    private final MemberInfoDao memberInfoDao;
    private final OrderDao orderDao;
    private final OrderByProductDao orderByProductDao;
    private final ProductTableDao productTableDao;
    private final UserDao userDao;
    private final FileInfoDao fileInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        investTableDaoConfig = daoConfigMap.get(InvestTableDao.class).clone();
        investTableDaoConfig.initIdentityScope(type);

        memberInfoDaoConfig = daoConfigMap.get(MemberInfoDao.class).clone();
        memberInfoDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        orderByProductDaoConfig = daoConfigMap.get(OrderByProductDao.class).clone();
        orderByProductDaoConfig.initIdentityScope(type);

        productTableDaoConfig = daoConfigMap.get(ProductTableDao.class).clone();
        productTableDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        investTableDao = new InvestTableDao(investTableDaoConfig, this);
        memberInfoDao = new MemberInfoDao(memberInfoDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        orderByProductDao = new OrderByProductDao(orderByProductDaoConfig, this);
        productTableDao = new ProductTableDao(productTableDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);

        registerDao(InvestTable.class, investTableDao);
        registerDao(MemberInfo.class, memberInfoDao);
        registerDao(Order.class, orderDao);
        registerDao(OrderByProduct.class, orderByProductDao);
        registerDao(ProductTable.class, productTableDao);
        registerDao(User.class, userDao);
        registerDao(FileInfo.class, fileInfoDao);
    }
    
    public void clear() {
        investTableDaoConfig.clearIdentityScope();
        memberInfoDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        orderByProductDaoConfig.clearIdentityScope();
        productTableDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        fileInfoDaoConfig.clearIdentityScope();
    }

    public InvestTableDao getInvestTableDao() {
        return investTableDao;
    }

    public MemberInfoDao getMemberInfoDao() {
        return memberInfoDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public OrderByProductDao getOrderByProductDao() {
        return orderByProductDao;
    }

    public ProductTableDao getProductTableDao() {
        return productTableDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

}
