package com.lz.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lz.bean.MemberInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEMBER_INFO".
*/
public class MemberInfoDao extends AbstractDao<MemberInfo, Long> {

    public static final String TABLENAME = "MEMBER_INFO";

    /**
     * Properties of entity MemberInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Uid = new Property(0, Long.class, "uid", true, "_id");
        public final static Property WealthPoint = new Property(1, Long.class, "WealthPoint", false, "WEALTH_POINT");
        public final static Property Grade = new Property(2, Integer.class, "grade", false, "GRADE");
    }


    public MemberInfoDao(DaoConfig config) {
        super(config);
    }
    
    public MemberInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEMBER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: uid
                "\"WEALTH_POINT\" INTEGER," + // 1: WealthPoint
                "\"GRADE\" INTEGER);"); // 2: grade
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEMBER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MemberInfo entity) {
        stmt.clearBindings();
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(1, uid);
        }
 
        Long WealthPoint = entity.getWealthPoint();
        if (WealthPoint != null) {
            stmt.bindLong(2, WealthPoint);
        }
 
        Integer grade = entity.getGrade();
        if (grade != null) {
            stmt.bindLong(3, grade);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MemberInfo entity) {
        stmt.clearBindings();
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(1, uid);
        }
 
        Long WealthPoint = entity.getWealthPoint();
        if (WealthPoint != null) {
            stmt.bindLong(2, WealthPoint);
        }
 
        Integer grade = entity.getGrade();
        if (grade != null) {
            stmt.bindLong(3, grade);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MemberInfo readEntity(Cursor cursor, int offset) {
        MemberInfo entity = new MemberInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uid
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // WealthPoint
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // grade
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MemberInfo entity, int offset) {
        entity.setUid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWealthPoint(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setGrade(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MemberInfo entity, long rowId) {
        entity.setUid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MemberInfo entity) {
        if(entity != null) {
            return entity.getUid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MemberInfo entity) {
        return entity.getUid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
